interface ProjectsPageData {
  title: string;
  description: string;
  url: string;
}

export const projectsPageData: ProjectsPageData[] = [
  {
    title: "React Dialogue Editor",
    description: "A node-based editor designed for game developers to craft narratives.",
    url: "https://github.com/Varollo/react-dialogue-editor"
  },

  {
    title: "Aseprite Importer",
    description: "A .NET and MonoGame library to load the Json data generated by the pixel art software Aseprite, when exporting a sprite sheet.",
    url: "https://github.com/Varollo/aseprite-importer"
  },

  {
    title: "Yaml Dialogue Lib",
    description: "A .NET library intended to interpret a .yaml file for game development.",
    url: "https://github.com/Varollo/YamlDialogueLib"
  }
]