import { Link } from "react-router-dom";
import Window from "../../components/Window/Window";

import "./ProjectsPage.css";

const ProjectsPage = () => {
  return (
    <Window title="Projects" mode="dark">
      <div className="projectsWindow">
        <p>
          <span className="terminalTxt">varollo@Gabriel-Carollo:</span> $ ls
        </p>

        <div className="projectHighlight">
          <h2>Aseprite Importer</h2>
          <div className="projectDescription">
            <p>
              A .NET and MonoGame library to load the Json data generated by the
              pixel art software Aseprite, when exporting a sprite sheet.
            </p>
            <Link to="https://github.com/Varollo/aseprite-importer">
              Open on GitHub...
            </Link>
          </div>
        </div>

        <div className="projectHighlight">
          <h2>Yaml Dialogue Lib</h2>
          <div className="projectDescription">
            <p>
              A .NET library intended to interpret a .yaml file for game
              development.
            </p>
            <Link to="https://github.com/Varollo/YamlDialogueLib">
              Open on GitHub...
            </Link>
          </div>
        </div>

        <p>
          <span className="terminalTxt">varollo@Gabriel-Carollo:</span> $_
        </p>
      </div>
    </Window>
  );
};

export default ProjectsPage;
